parserOptions:
  project: ./tsconfig.json
rules:
  no-console:
    - error
    - allow:
        - info
        - error
        - warn
  '@typescript-eslint/no-restricted-imports':
    - error
    - patterns:
